### PR TITLE
Save request and response for logging purposes

### LINKED ISSUE #13: Save request and response for logging purposes

### PR DESCRIPTION
**Pull request by evgenius**
Fixes #13

### CODE REVIEW

**Comment by oschwald** [comment]
Not sure I follow the query string question. I'd be more inclined to accept this if it passed in an optional logger object to the constructor to use instead of just adding some state to the object. That said, as far as I know, there isn't really a standard logger object interface in the PHP world.

**Comment by sonnysavage** [comment]
RE: "standard logger object interface in the PHP world"

There is one, and it's PSR-3 from the PHP-FIG: https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md

**Comment by oschwald** [comment]
Ah, cool. I missed that PSR. I'd accept a patch that took an optional logger using that interface and logged at the `info` or lower level.

**Comment by oschwald** [comment]
Closing for the aforementioned reasons.

**Pull request closed without merging**
