### PR TITLE
use of _SERVER instead of hardcoding

### PR DESCRIPTION
**Pull request by nimasdj**
Use of _SERVER instead of hardcoding.

### CODE REVIEW

**Comment by oschwald** [comment]
Thanks!

**Comment by nimasdj** [comment]
Welcome. :-)

**Comment by nimasdj** [comment]
I still insist to release a major version with namespace. As this versio n will still be alive minimum 2 years.

**Comment by nimasdj** [comment]
@oschwald if you don't want to use psr4 namespace, at least please use classmap instead of files autoloader https://github.com/maxmind/ccfd-api-php/pull/24

**Pull request merged**
